### ISSUE TITLE
Demodulation for other inmarsat signals

### ISSUE THREAD

**Issue by shinetots** [jontio/JAERO#11]
Hi. I found jaero amazing! I've just tested jaero with these sample signals found at http://www.sigidwiki.com/wiki/Inmarsat_Aero . I would like to ask if jaero can also demodulate/decode other inmarsat signals like Inmarsat-B and C. Thanks!

**Comment by jontio** [comment]
Hi,

 

I’m glad you like JAERO. Inmarsat-B and C use different modulation techniques so JAERO can’t demodulate them, they also have different coding so JAERO also can’t decode them either. Inmarsat-C uses BPSK (easy to demodulate) Inmarsat-C uses some sort of multi frequency thing.

 

Cheers,

Jonti

**Comment by shinetots** [comment]
I see.  Is jaero exclusive only for aero signals? Are there any other inmarsat signals that can be demodulated through jaero? How about adding another demodulator class in the source code?

**Comment by jontio** [comment]
Yup JAERO is just for Aero data. JAERO still can't decode any Aero audio Aero signals though.

Rather than adding another demodlator class and decoder class I would write another program for non aero signals; that would make more sense. I would like to make an Inmarsat-C demodulator and decoder one days but I currently don't have much free time for the next 6 months at least.

There is voi
