### ISSUE TITLE
automatic locking at c-channels not working

### ISSUE THREAD

**Issue by PeterMaxu** [jontio/JAERO#32]
When new c-channels are activ, jaero often does not lock at them, i have to do it manually.
Once it locked at them, with manual help, it mostly does not loose the lock, even if a other channel overlaps it a bit. jeara shows EbNo of 12 db.

**Comment by KR0SIV** [comment]
I've noticed this as well, sometimes it locks just fine but most of the time it requires me manually selecting the channel in the window a couple times for it to recognize there is something there.

**Comment by jontio** [comment]
Yup. The 8400bps demodulator needs improving both with locking and with adjacent channel rejection. I didn't write the 8400bps demodulator so will need to look at how it works. I'll also need a suitable test recording to work with (one with 2 active adjacent channels). Then I'll need a bit of free time. I've got this planned but just don't have the time for the rest of the month. In the meantime if someone attaches an baseband/audio file of 2 adjacent 8400bps signals (the baseband or sound of from something like SDR# covering the 2 channels that I can play on a loop) which is a problematic signal that would be one less thing I have to do.

**Comment by jlxsolutions** [comment]
>  I'll also need a suitable test recording to work with (one with 2 active adjacent channels). Then I'll need a bit of free time.
https://drive.google.com/file/d/1-pRBdisBBHh1UaUAv87HQ92J_CgH6fCP/view?usp=drive_web here ya go for the IQ

**Comment by jontio** [comment]
Thanks for that. Ekks they are some weak crowded signals and very sort lived. Interesting, playing them back I don't get as much trouble with adjacent channels compared to when I did a real life test. Very odd.

Just out of interest, for signals that lock have no sound and vanish after a few seconds... When someone makes a C-channel call it will ring like a typical telephone. The ringing sound is encoded differently than normal speech and libaeroambe doesn't support the ringing sound. So these silent signals are people calling someone but no one picks up on the other end. 

I'll see what I can do with your recording. As I said I don't have much time this month so any improvements wont be seen till January at the earliest. Figures crossed it's not too difficult.

**Comment by jontio** [comment]
Hi all,

I been given two recordings and that is what I've been working on for the last few days. These are the only recordings I've tested the demodulator on. One is the very week one from jlxsolutions above and the other one is a very strong one someone emailed me directly which I have also found invaluable to work with. The more the better really, anyway I got two and hopefully that has been enough to get a realistic sample of signals.

I have pushed the new changes...
https://github.com/jontio/JAERO/commit/de4c98acfe351506c24ec56a4dde9f0d2a76f303 

The changes are...
8400bps channels use a raised cosine weighting for locking. 8400bps
channels use large complex fasrfir RRC filter b4 the mixer shifted to
the approxmate place of the signal rather than the small slow fir. The
RRC filter for 8400bps channels is 0.6 rather than 1.0. Slowed frequency
agility of 8400bps signals. Added detection for stable non dcd state (a
bit slow but should be ok), this  uses the dcd from aerol, if
mse<threshold and !dcd for too long then starts using coarse freq
estimates again. Added AES and GES to the audio file logging names when
availible. Delete audio files then than 10k. Changed audio logging time
to 2 secs. Reduced 8400bps symbol resonator from 35hz to 10hz. Allow
shifting 8400bps signal below where they should go (ie center freq
<4200Hz) still don't do this move it up a bit.

Oh and I just remember another one was optimizing the sample time better, it was somewhat off before.

It addresses a lot more than just the automatic locking. It won't get permanently stuck in that silly state that it used to but it is a little slow and takes a few seconds to get unstuck and try again. The reason it's a little slow is it has to wait for the DCD LED to go off and that uses the sub data which is very slow on the 8400bps channels as most of it is used for audio. Anyway I'm sure it'll be fine.

I don't think it affects anything else but the 8400 channels but it's possible I made a mistake. I haven't tested it on anything else but 8400 channels so that should really be done. If the people who can compile from source can test it out over the next few days and let me know if they find any problems that would be good. If I get the thumbs up or if I hear back from no one I'll package it up and make it the new release this weekend.

Cheers,
Jonti

**Comment by jontio** [comment]
Okay I have published the new release so hopefully that should that should do the trick. I didn't hear back from anyone. I tried it out for a day and seems okay. I had actually written that demodulator, I hadn't realized that Jeroen was using the same one. Anyway, I will wait to hear feedback.
