### ISSUE TITLE
Database not being recognised

### ISSUE THREAD

**Issue by nzradar** [jontio/JAERO#48]
Hi Jonti,
I am having some problems understanding the plane database philosophy.  I know the downloaded db is not your remit so I would like to understand the required format and location for the db.

At the moment when I go to Settings in JAERO and click the download button JAERO reports 1 database successfully downloaded but in fact nothing arrives in either my download folder or the JAERO db location specified in the Settings.  If I go directly to https://junzisun.com/adb/download I can get a zip file that contains aircrafts_db.csv but extracting that into the JAERO directory doesn't help as I get an error "Database file aircrafts_dump.db missing. Download first."  So if I rename that file aircrafts_dump.db I get this error "Error: file is not a database Unable to execute statement".  If I open that file in a text editor these are the first few lines:

icao,regid,mdl,type,operator
004003,z-wpb,b732,Boeing 737-2N0,Air Zimbabwe
00400c,z-faa,b735,Boeing 737-55S,FlyAfrica
00400e,z-fab,b735,Boeing 737-55S,FlyAfrica
00400f,z-fje,a319,Airbus A319-131,Fastjet Zimbabwe

Can you advise me what I need to have or do to get a working database?

Cheers,
Michael
Palmerston North

**Comment by jontio** [comment]
Hi Michael,

This is issue #47 . What's happening is the guy who's does the db has put in a redirect and the download unit in JAERO isn't following the redirect but rather just downloading the redirect message. Your web browser is following the redirect. To fix it change the url to read https://junzis.com/adb/download . I'm planning on making that the default url in future. However from others it seems that the database may not be maintained any more so that's another problem. If you find a publicly available db on the net you manage to find someone to maintain one let me know.

For importing a db in JAERO it expects it in a csv format and a particular name but off the top of my head I can't remember the name. something like aircraft-new.csv, it will be mentioned in the code or in one of the issues.

Cheers,
Jonti

**Comment by jontio** [comment]
now uses basestation format
