### ISSUE TITLE
Plane log: Cant open SQL database 

### ISSUE THREAD

**Issue by DickvanNoort** [jontio/JAERO#65]
Hi Jonti,
When using the latest Windows package 1.0.4.13-18 a 'Cant open SQL database' message is displayed when using the Plane log window.

This worked fine using the 1.0.4.13-alpha  package.

Finally it proved that replacing the content of the sqldrivers directory  fixed the problem.
Not sure which driver is causing it, but I noticed that at the size of qsqlite.dll, although showing the same version 5.15.2.0, is very different 1.31 MB vs 154 KB.

Cheers,
Dick

**Comment by jontio** [comment]
Hi Dick,

Thanks for spotting that, much appreciated. It seems they moved some of the functions in qsqlite.dll to libsqlite3-0.dll so hence the smaller size. I hadn't added libsqlite3-0.dll to the package. I've now added that dll too so that should fix the problem. The new release is in the usual place https://github.com/jontio/JAERO/releases/tag/latest .

Cheers,
Jonti

**Comment by DickvanNoort** [comment]
Hi Jonti,
Thanks for this instant response.
Much appreciated.

Will have a go at it after a late X-mas lunch. 
Not sure where you live but my local time is UTC + 1.  :-) 

Cheers and have a happy and above all healthy new year,
Dick

**Comment by DickvanNoort** [comment]
Just confirmed that the 'Cant open SQL database' problem on Windows is solved. As I only have very limited satellite reception I used a saved plane-log which I also used to reproduce the problem.

Thanks,
Dick
